---
- name: Create and start Nexus container
  docker_container:
    name: nexus
    state: started
    image: sonatype/nexus3
    ports:
     - "8501:8081"
    volumes:
    - nexus-data:/nexus-data

- name: Configure NGINX reverse proxy for Nexus
  template:
    src: nexus.conf.j2
    dest: /etc/nginx/conf.d/nexus.conf
  register: changedProxy

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded
  when: changedProxy.changed