---
- name: Install docker dependencies
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add docker's APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Get kernel version
  shell: uname -r
  register: kernel_version

- name: Install linux-image-extra-* packages
  apt: name={{item}} state=latest
  with_items:
    #- linux-image-extra-{{kernel_version.stdout}}
    - linux-image-extra-virtual

- name: Remove previous docker versions
  apt: name={{item}} state=absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Install Docker Comunity Edition
  apt: name=docker-ce state=present

- name: Start docker service
  service:
    name: docker
    state: started

- name: Install docker-compose
  include: docker-compose-install.yml
