---
- name: Check if Terraform is installed
  stat:
    path: /usr/local/bin/terraform
  register: terraform_st

- name: Download Terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
    dest: /tmp/terraform.zip
    checksum: sha256:5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2
  when: not terraform_st.stat.exists

- name: Unzip Terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /tmp/
    remote_src: yes
  when: not terraform_st.stat.exists

- name: Copy Terraform binary to /usr/local/bin
  copy:
    src: /tmp/terraform
    dest: /usr/local/bin/terraform
    mode: a+rx
    remote_src: yes
